# Generated by Django 4.2.9 on 2024-01-07 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('hotel_address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('hotel_star', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('pincode', models.BigIntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)])),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
    ]
