# Generated by Django 4.2.9 on 2024-01-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
